apiVersion: apps/v1
kind: Deployment
metadata:
  name: springweb
  labels:
    app: springweb
spec:
  selector:
    matchLabels:
      app: springweb
  template:
    metadata:
      labels:
        app: springweb
    spec:
      containers:
        - name: springweb-app
          image: sumanth17121988/springpetclinic:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxHeapSize=1024m\
                      -Dcom.sun.management.jmxremote \
                      -Dcom.sun.management.jmxremote.authenticate=false \
                      -Dcom.sun.management.jmxremote.ssl=false \
                      -Dcom.sun.management.jmxremote.local.only=false \
                      -Dcom.sun.management.jmxremote.port=9010 \
                      -Dcom.sun.management.jmxremote.rmi.port=9010 \
                      -Djava.rmi.server.hostname=127.0.0.1"
