apiVersion: v1
kind: Service
metadata:
  name: "springweb-service"
  namespace: "default"
  labels:
    app: "springweb"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: "springweb"
  type: LoadBalancer
